// Single source of truth for the glossary.
// Powers: (1) the glossary page, (2) its search box, (3) auto-linking of every
// term wherever it appears across the wiki.
// MAINTENANCE: whenever a medical term appears that a non-specialist wouldn't
// know, add an entry here. `aliases` are alternate spellings/abbreviations that
// should also link to this definition. Keep definitions in plain language.
var GLOSSARY = [
  { term: "IgA nephropathy", aliases: ["IgAN", "Berger's disease"], def: "A kidney disease in which a malformed antibody (IgA1) builds up in the kidney's filters, causing inflammation and scarring. The focus of this wiki; also called Berger's disease." },
  { term: "Galactose-deficient IgA1", aliases: ["Gd-IgA1"], def: "A faulty version of the IgA1 antibody missing sugar molecules (galactose) on its hinge. This 'malformed protein' is the root trigger of IgA nephropathy." },
  { term: "IgA1", aliases: ["immunoglobulin A1"], def: "A type of antibody especially active at mucosal surfaces such as the gut. A mis-sugared version of it causes IgA nephropathy." },
  { term: "Antibody", aliases: ["antibodies"], def: "A Y-shaped protein the immune system makes to recognize and bind specific targets. IgA1 is one class of antibody." },
  { term: "GalNAc", aliases: ["N-acetylgalactosamine"], def: "A sugar molecule attached to the IgA1 hinge. When galactose fails to cover it, the exposed GalNAc becomes a target the immune system attacks." },
  { term: "Galactose", def: "A simple sugar normally added to the IgA1 hinge. Its absence is what makes IgA1 'galactose-deficient' and disease-causing." },
  { term: "Glycosylation", aliases: ["O-glycosylation", "O-glycan", "O-glycans", "glycan", "glycans"], def: "The attaching of sugar chains to a protein. Faulty glycosylation of IgA1 (too little galactose) is central to IgA nephropathy." },
  { term: "C1GALT1", def: "The enzyme that adds galactose to the IgA1 hinge. Reduced activity leaves IgA1 galactose-deficient." },
  { term: "Cosmc", aliases: ["C1GALT1C1"], def: "A helper protein (chaperone) the C1GALT1 enzyme needs to work. When Cosmc is silenced, galactosylation of IgA1 fails." },
  { term: "Glycosyltransferase", aliases: ["glycosyltransferases"], def: "An enzyme that attaches sugar molecules to proteins. C1GALT1 is one example." },
  { term: "Sialyltransferase", aliases: ["ST6GalNAc-II"], def: "An enzyme that caps the IgA1 sugar with sialic acid; when overactive it blocks galactose from being added, worsening the defect." },
  { term: "Hinge region", aliases: ["hinge"], def: "The flexible middle section of the IgA1 antibody that carries the sugar chains involved in the disease." },
  { term: "APRIL", def: "A signaling molecule (cytokine) that stimulates the immune cells producing faulty IgA1. Blocking it is a leading treatment strategy." },
  { term: "BAFF", def: "A signaling molecule closely related to APRIL that supports antibody-producing B cells; often targeted together with APRIL." },
  { term: "TACI-Fc", def: "A lab-made decoy protein that soaks up both APRIL and BAFF, used as a drug (e.g., atacicept, telitacicept, povetacicept)." },
  { term: "Monoclonal antibody", aliases: ["mAb", "monoclonal antibodies"], def: "A lab-made antibody engineered to bind one specific target. Many IgAN drugs are monoclonal antibodies (names ending in '-mab')." },
  { term: "Autoantibody", aliases: ["autoantibodies", "anti-glycan antibody", "anti-glycan antibodies"], def: "An antibody that mistakenly targets the body's own molecules. In IgAN, autoantibodies bind the faulty IgA1." },
  { term: "Immune complex", aliases: ["immune complexes"], def: "A clump formed when antibodies bind their target. In IgAN, IgA1 plus autoantibodies form clumps that lodge in the kidney." },
  { term: "B cell", aliases: ["B cells", "B-cell"], def: "A white blood cell that produces antibodies. In IgAN, certain B cells make the faulty IgA1." },
  { term: "Plasma cell", aliases: ["plasma cells", "plasmablast", "plasmablasts"], def: "A mature B cell that mass-produces antibodies. Some IgAN drugs aim to remove the plasma cells making faulty IgA1." },
  { term: "CD38", def: "A marker protein on plasma cells; drugs such as felzartamab target it to deplete antibody-producing cells." },
  { term: "Cytokine", aliases: ["cytokines"], def: "A small signaling protein immune cells use to communicate (e.g., APRIL, IL-6). Several drive IgAN." },
  { term: "Mucosal immunity", aliases: ["mucosal"], def: "The part of the immune system guarding surfaces like the gut and airways, where the faulty IgA1 is thought to originate." },
  { term: "Peyer's patches", def: "Clusters of immune tissue in the gut lining where much IgA is made; a target of the gut-release drug Nefecon/budesonide." },
  { term: "Microbiome", aliases: ["microbiota"], def: "The community of bacteria living in the gut, which can influence the mucosal immune signals behind IgAN." },
  { term: "Toll-like receptor", aliases: ["TLR", "TLR9", "TLR4"], def: "Immune sensors that detect microbes; their activation can trigger the faulty IgA1 response." },
  { term: "Interleukin", aliases: ["IL-6", "IL-4"], def: "A family of cytokines. IL-6 and IL-4 push immune cells to make more galactose-deficient IgA1." },
  { term: "STAT3", def: "An internal signaling switch activated by IL-6; overactivation increases production of faulty IgA1." },
  { term: "TGF-β", aliases: ["TGF-beta", "TGF-β1", "transforming growth factor beta"], def: "A signaling protein that both alters IgA1 sugars and is a master driver of tissue scarring (fibrosis)." },
  { term: "GWAS", aliases: ["genome-wide association study"], def: "A study that scans many people's DNA to find gene variants linked to a trait or disease." },
  { term: "Epigenetic", aliases: ["epigenetically", "hypermethylation", "methylation"], def: "Chemical marks on DNA that switch genes on or off without changing the DNA sequence. Silencing of Cosmc by such marks contributes to IgAN and is potentially reversible." },
  { term: "Heritability", aliases: ["heritable"], def: "The share of a trait's variation explained by genetics. Faulty-IgA1 levels are moderately heritable." },
  { term: "Mesangium", aliases: ["mesangial", "mesangial cells"], def: "The supportive tissue in the center of the kidney's filter (glomerulus) where immune complexes deposit in IgAN." },
  { term: "Glomerulus", aliases: ["glomeruli", "glomerular"], def: "A tiny ball of blood vessels in the kidney that filters blood to form urine. The main site of injury in IgAN." },
  { term: "Glomerulonephritis", def: "Inflammation of the kidney's filtering units (glomeruli). IgAN is the most common primary form worldwide." },
  { term: "Glomerulosclerosis", def: "Scarring of the glomeruli that permanently reduces their filtering ability." },
  { term: "Fibrosis", aliases: ["fibrotic", "profibrotic", "anti-fibrotic", "antifibrotic"], def: "The build-up of scar tissue that replaces healthy tissue and impairs organ function." },
  { term: "Interstitial fibrosis", aliases: ["tubulointerstitial fibrosis", "tubulointerstitial"], def: "Scarring in the kidney tissue between the tubules; a key marker of irreversible damage." },
  { term: "Nephron", aliases: ["nephrons"], def: "The kidney's basic filtering unit (about a million per kidney). Lost nephrons do not regrow." },
  { term: "Podocyte", aliases: ["podocytes"], def: "Specialized cells that wrap the glomerular filter; their loss is an early, critical step in kidney damage." },
  { term: "Glomerular basement membrane", aliases: ["GBM"], def: "The thin filtering barrier of the glomerulus." },
  { term: "Myofibroblast", aliases: ["myofibroblasts"], def: "The main scar-producing cell; getting it to switch off or die is key to reversing fibrosis." },
  { term: "Pericyte", aliases: ["pericytes"], def: "A cell wrapping small blood vessels that can transform into a scar-producing myofibroblast after injury." },
  { term: "Epithelial-mesenchymal transition", aliases: ["EMT"], def: "A process where lining (epithelial) cells take on migratory, scar-associated traits; its role in kidney fibrosis is debated." },
  { term: "Complement", def: "A cascade of blood proteins that amplifies immune attack; over-activation damages the kidney in IgAN." },
  { term: "Alternative pathway", def: "One of three ways the complement cascade switches on; a major driver of injury in IgAN (target of iptacopan)." },
  { term: "Lectin pathway", def: "Another complement activation route, triggered by sugars; targeted by narsoplimab." },
  { term: "Classical pathway", def: "The antibody-triggered complement route; largely spared in IgAN." },
  { term: "Factor B", def: "A complement protein essential to the alternative pathway; blocked by the drug iptacopan." },
  { term: "MASP-2", def: "An enzyme that switches on the lectin complement pathway; target of narsoplimab." },
  { term: "C3", def: "A central complement protein; a hub of the cascade and a drug target (pegcetacoplan)." },
  { term: "C5", def: "A late-stage complement protein driving inflammation; target of anti-C5 drugs (ravulizumab, cemdisiran)." },
  { term: "Proteinuria", def: "Protein leaking into the urine — a sign of a damaged kidney filter and the main measure of IgAN activity." },
  { term: "UPCR", aliases: ["urine protein-creatinine ratio"], def: "A urine test that quantifies proteinuria; commonly used as a clinical-trial endpoint." },
  { term: "eGFR", aliases: ["estimated glomerular filtration rate"], def: "An estimate of how well the kidneys filter blood; the key number for tracking kidney function over time." },
  { term: "Chronic kidney disease", aliases: ["CKD"], def: "Long-term loss of kidney function; advanced IgAN progresses to CKD." },
  { term: "Acute kidney injury", aliases: ["AKI"], def: "A sudden, often reversible drop in kidney function; repeated episodes can lead to scarring." },
  { term: "RAAS", aliases: ["renin-angiotensin-aldosterone system", "RAS blockade"], def: "A hormone system controlling blood pressure and kidney filtration pressure; blocking it protects the kidney." },
  { term: "ACE inhibitor", aliases: ["ACEi", "ACE inhibitors"], def: "A blood-pressure drug that lowers filter pressure and proteinuria; foundational IgAN therapy." },
  { term: "ARB", aliases: ["angiotensin receptor blocker", "ARBs"], def: "A blood-pressure drug with kidney-protective effects similar to ACE inhibitors." },
  { term: "Endothelin", def: "A powerful blood-vessel-constricting molecule; blocking its receptor (sparsentan, atrasentan) lowers proteinuria." },
  { term: "Angiotensin", def: "A hormone that raises blood pressure and filter pressure; a target of ACE inhibitors and ARBs." },
  { term: "SGLT2 inhibitor", aliases: ["SGLT2", "SGLT2i", "dapagliflozin"], def: "A drug class originally for diabetes that broadly protects the kidneys and slows functional decline." },
  { term: "Mineralocorticoid receptor antagonist", aliases: ["MRA", "finerenone"], def: "A drug that blocks a hormone receptor to reduce kidney inflammation and scarring." },
  { term: "Corticosteroid", aliases: ["steroid", "budesonide"], def: "An anti-inflammatory drug; a gut-targeted form (budesonide / Nefecon) treats IgAN at its mucosal source." },
  { term: "siRNA", aliases: ["small interfering RNA", "RNA interference"], def: "A drug type that silences a specific gene to lower its protein (e.g., cemdisiran lowers complement C5)." },
  { term: "Biomarker", aliases: ["biomarkers"], def: "A measurable indicator of disease or drug effect (e.g., serum Gd-IgA1)." },
  { term: "Pharmacodynamic", aliases: ["pharmacodynamic readout", "PD readout"], def: "Relating to a drug's measurable effect on the body; a 'PD readout' shows a drug is engaging its target." },
  { term: "Accelerated approval", def: "A faster FDA pathway that clears a drug based on an early marker (like proteinuria) before long-term outcomes are fully proven." },
  { term: "PDUFA", aliases: ["PDUFA date"], def: "The target date by which the FDA aims to decide on a drug application." },
  { term: "KDIGO", def: "The international body that issues kidney-disease treatment guidelines." },
  { term: "FSGS", aliases: ["focal segmental glomerulosclerosis"], def: "Another glomerular disease marked by scarring; referenced here for its podocyte-repair research." }
];
